package Prueba_Empleado;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class ViewEmpleado extends JFrame{
    
    private JPanel contenedor;
    
    private JLabel lblfolioEmpleado;
    private JLabel lblnombre;
    private JLabel lblapellidos;
    private JLabel lblcorreoElectronico;
    private JLabel lbltelefono;
    private JLabel lbloficina;
    private JLabel lbldepartamento;
    private JLabel lbltipoContrato;
    private JLabel lblestado;
    private JLabel lblciudad;
    private JLabel lblcalle;
    private JLabel lblcodigoPostal;
    private JLabel lblfechaDeNacimiento;
    private JLabel lblpuestoDeTrabajo;
    private JLabel lblgenero;
    private JLabel lblsueldo;
    private JLabel lblcurp;
    private JLabel lblrfc;
    private JLabel lblcontraseña;
    
    protected JTextField txtfolioEmpleado;
    protected JTextField txtnombre;
    protected JTextField txtapellidos;
    protected JTextField txtcorreoElectronico;
    protected JTextField txttelefono;
    protected JTextField txtoficina;
    protected JTextField txtdepartamento;
    protected JTextField txttipoContrato;
    protected JTextField txtestado;
    protected JTextField txtciudad;
    protected JTextField txtcalle;
    protected JTextField txtcodigoPostal;
    protected JTextField txtfechaDeNacimiento;
    protected JTextField txtpuestoDeTrabajo;
    protected JTextField txtgenero;
    protected JTextField txtsueldo;
    protected JTextField txtcurp;
    protected JTextField txtrfc;
    protected JTextField txtcontraseña;
    
    protected JButton btnAdd;
    protected JButton btnDel;
    protected JButton btnUpd;
    
    private JScrollPane scroll;
    protected Object[][] datos;
    protected String[] cabecera;
    protected DefaultTableModel dtm;
    protected JTable tabla;
    
    public ViewEmpleado(){
        setBounds(350,250,1000,900);
        setTitle("Tienda Super");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        contenedor = new JPanel();
        getContentPane().add(contenedor);
        SpringLayout sp = new SpringLayout();
        contenedor.setLayout(sp);
        
        lblfolioEmpleado = new JLabel("Folio empleado");
        contenedor.add(lblfolioEmpleado);
        sp.putConstraint(SpringLayout.NORTH, lblfolioEmpleado, 20, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, lblfolioEmpleado, 10, SpringLayout.WEST, contenedor);
        lblnombre = new JLabel("Nombre");
        contenedor.add(lblnombre);
        sp.putConstraint(SpringLayout.NORTH, lblnombre,40, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, lblnombre, 10, SpringLayout.WEST, contenedor);
        lblapellidos = new JLabel("Apellidos");
        contenedor.add(lblapellidos);
        sp.putConstraint(SpringLayout.NORTH, lblapellidos,60, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, lblapellidos, 10, SpringLayout.WEST, contenedor);
        lblcorreoElectronico = new JLabel("Correo electronico");
        contenedor.add(lblcorreoElectronico);
        sp.putConstraint(SpringLayout.NORTH, lblcorreoElectronico,80, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, lblcorreoElectronico, 10, SpringLayout.WEST, contenedor);
        lbltelefono = new JLabel("Telefono");
        contenedor.add(lbltelefono);
        sp.putConstraint(SpringLayout.NORTH, lbltelefono,100, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, lbltelefono, 10, SpringLayout.WEST, contenedor);
        lbloficina = new JLabel("Oficina");
        contenedor.add(lbloficina);
        sp.putConstraint(SpringLayout.NORTH, lbloficina,120, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, lbloficina, 10, SpringLayout.WEST, contenedor);
        lbldepartamento = new JLabel("Departamento");
        contenedor.add(lbldepartamento);
        sp.putConstraint(SpringLayout.NORTH, lbldepartamento,140, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, lbldepartamento, 10, SpringLayout.WEST, contenedor);
        lbltipoContrato = new JLabel("Tipo de Contrato");
        contenedor.add(lbltipoContrato);
        sp.putConstraint(SpringLayout.NORTH, lbltipoContrato,160, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, lbltipoContrato, 10, SpringLayout.WEST, contenedor);
        lblestado = new JLabel("Estado");
        contenedor.add(lblestado);
        sp.putConstraint(SpringLayout.NORTH, lblestado,180, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, lblestado, 10, SpringLayout.WEST, contenedor);
        lblciudad = new JLabel("Ciudad");
        contenedor.add(lblciudad);
        sp.putConstraint(SpringLayout.NORTH, lblciudad,200, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, lblciudad, 10, SpringLayout.WEST, contenedor);
        lblcalle = new JLabel("Calle");
        contenedor.add(lblcalle);
        sp.putConstraint(SpringLayout.NORTH, lblcalle,220, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, lblcalle, 10, SpringLayout.WEST, contenedor);
        lblcodigoPostal = new JLabel("Codigo Postal");
        contenedor.add(lblcodigoPostal);
        sp.putConstraint(SpringLayout.NORTH, lblcodigoPostal,240, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, lblcodigoPostal, 10, SpringLayout.WEST, contenedor);
        lblfechaDeNacimiento = new JLabel("Fecha de Nacimiento");
        contenedor.add(lblfechaDeNacimiento);
        sp.putConstraint(SpringLayout.NORTH, lblfechaDeNacimiento,260, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, lblfechaDeNacimiento, 10, SpringLayout.WEST, contenedor);
        lblpuestoDeTrabajo = new JLabel("Puesto de trabajo");
        contenedor.add(lblpuestoDeTrabajo);
        sp.putConstraint(SpringLayout.NORTH, lblpuestoDeTrabajo,280, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, lblpuestoDeTrabajo, 10, SpringLayout.WEST, contenedor);
        lblgenero = new JLabel("Genero");
        contenedor.add(lblgenero);
        sp.putConstraint(SpringLayout.NORTH, lblgenero,300, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, lblgenero, 10, SpringLayout.WEST, contenedor);
        lblsueldo = new JLabel("Sueldo");
        contenedor.add(lblsueldo);
        sp.putConstraint(SpringLayout.NORTH, lblsueldo,320, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, lblsueldo, 10, SpringLayout.WEST, contenedor);
        lblcurp = new JLabel("CURP");
        contenedor.add(lblcurp);
        sp.putConstraint(SpringLayout.NORTH, lblcurp,340, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, lblcurp, 10, SpringLayout.WEST, contenedor);
        lblrfc = new JLabel("RFC");
        contenedor.add(lblrfc);
        sp.putConstraint(SpringLayout.NORTH, lblrfc,360, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, lblrfc, 10, SpringLayout.WEST, contenedor);
        lblcontraseña = new JLabel("Contraseña");
        contenedor.add(lblcontraseña);
        sp.putConstraint(SpringLayout.NORTH, lblcontraseña,380, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, lblcontraseña, 10, SpringLayout.WEST, contenedor);
        
        txtfolioEmpleado = new JTextField();
        contenedor.add(txtfolioEmpleado);
        sp.putConstraint(SpringLayout.NORTH, txtfolioEmpleado, 20, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, txtfolioEmpleado, 120, SpringLayout.WEST, contenedor);
        sp.putConstraint(SpringLayout.EAST, txtfolioEmpleado, 350, SpringLayout.WEST, contenedor);
        txtnombre = new JTextField();
        contenedor.add(txtnombre);
        sp.putConstraint(SpringLayout.NORTH, txtnombre, 40, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, txtnombre, 120, SpringLayout.WEST, contenedor);
        sp.putConstraint(SpringLayout.EAST, txtnombre, 350, SpringLayout.WEST, contenedor);
        txtapellidos = new JTextField();
        contenedor.add(txtapellidos);
        sp.putConstraint(SpringLayout.NORTH, txtapellidos, 60, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, txtapellidos, 120, SpringLayout.WEST, contenedor);
        sp.putConstraint(SpringLayout.EAST, txtapellidos, 350, SpringLayout.WEST, contenedor);
        txtcorreoElectronico = new JTextField();
        contenedor.add(txtcorreoElectronico);
        sp.putConstraint(SpringLayout.NORTH, txtcorreoElectronico, 80, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, txtcorreoElectronico, 120, SpringLayout.WEST, contenedor);
        sp.putConstraint(SpringLayout.EAST, txtcorreoElectronico, 350, SpringLayout.WEST, contenedor);
        txttelefono = new JTextField();
        contenedor.add(txttelefono);
        sp.putConstraint(SpringLayout.NORTH, txttelefono, 100, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, txttelefono, 120, SpringLayout.WEST, contenedor);
        sp.putConstraint(SpringLayout.EAST, txttelefono, 350, SpringLayout.WEST, contenedor);
        txtoficina = new JTextField();
        contenedor.add(txtoficina);
        sp.putConstraint(SpringLayout.NORTH, txtoficina, 120, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, txtoficina, 120, SpringLayout.WEST, contenedor);
        sp.putConstraint(SpringLayout.EAST, txtoficina, 350, SpringLayout.WEST, contenedor);
        txtdepartamento = new JTextField();
        contenedor.add(txtdepartamento);
        sp.putConstraint(SpringLayout.NORTH, txtdepartamento, 140, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, txtdepartamento, 120, SpringLayout.WEST, contenedor);
        sp.putConstraint(SpringLayout.EAST, txtdepartamento, 350, SpringLayout.WEST, contenedor);
        txttipoContrato = new JTextField();
        contenedor.add(txttipoContrato);
        sp.putConstraint(SpringLayout.NORTH, txttipoContrato, 160, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, txttipoContrato, 120, SpringLayout.WEST, contenedor);
        sp.putConstraint(SpringLayout.EAST, txttipoContrato, 350, SpringLayout.WEST, contenedor);
        txtestado = new JTextField();
        contenedor.add(txtestado);
        sp.putConstraint(SpringLayout.NORTH, txtestado, 180, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, txtestado, 120, SpringLayout.WEST, contenedor);
        sp.putConstraint(SpringLayout.EAST, txtestado, 350, SpringLayout.WEST, contenedor);
        txtciudad = new JTextField();
        contenedor.add(txtciudad);
        sp.putConstraint(SpringLayout.NORTH, txtciudad, 200, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, txtciudad, 120, SpringLayout.WEST, contenedor);
        sp.putConstraint(SpringLayout.EAST, txtciudad, 350, SpringLayout.WEST, contenedor);
        txtcalle = new JTextField();
        contenedor.add(txtcalle);
        sp.putConstraint(SpringLayout.NORTH, txtcalle, 220, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, txtcalle, 120, SpringLayout.WEST, contenedor);
        sp.putConstraint(SpringLayout.EAST, txtcalle, 350, SpringLayout.WEST, contenedor);
        txtcodigoPostal = new JTextField();
        contenedor.add(txtcodigoPostal);
        sp.putConstraint(SpringLayout.NORTH, txtcodigoPostal, 240, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, txtcodigoPostal, 120, SpringLayout.WEST, contenedor);
        sp.putConstraint(SpringLayout.EAST, txtcodigoPostal, 350, SpringLayout.WEST, contenedor);
        txtfechaDeNacimiento = new JTextField();
        contenedor.add(txtfechaDeNacimiento);
        sp.putConstraint(SpringLayout.NORTH, txtfechaDeNacimiento, 260, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, txtfechaDeNacimiento, 120, SpringLayout.WEST, contenedor);
        sp.putConstraint(SpringLayout.EAST, txtfechaDeNacimiento, 350, SpringLayout.WEST, contenedor);
        txtpuestoDeTrabajo = new JTextField();
        contenedor.add(txtpuestoDeTrabajo);
        sp.putConstraint(SpringLayout.NORTH, txtpuestoDeTrabajo, 280, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, txtpuestoDeTrabajo, 120, SpringLayout.WEST, contenedor);
        sp.putConstraint(SpringLayout.EAST, txtpuestoDeTrabajo, 350, SpringLayout.WEST, contenedor);
        txtgenero = new JTextField();
        contenedor.add(txtgenero);
        sp.putConstraint(SpringLayout.NORTH, txtgenero, 300, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, txtgenero, 120, SpringLayout.WEST, contenedor);
        sp.putConstraint(SpringLayout.EAST, txtgenero, 350, SpringLayout.WEST, contenedor);
        txtsueldo = new JTextField();
        contenedor.add(txtsueldo);
        sp.putConstraint(SpringLayout.NORTH, txtsueldo, 320, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, txtsueldo, 120, SpringLayout.WEST, contenedor);
        sp.putConstraint(SpringLayout.EAST, txtsueldo, 350, SpringLayout.WEST, contenedor);
        txtcurp = new JTextField();
        contenedor.add(txtcurp);
        sp.putConstraint(SpringLayout.NORTH, txtcurp, 340, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, txtcurp, 120, SpringLayout.WEST, contenedor);
        sp.putConstraint(SpringLayout.EAST, txtcurp, 350, SpringLayout.WEST, contenedor);
        txtrfc = new JTextField();
        contenedor.add(txtrfc);
        sp.putConstraint(SpringLayout.NORTH, txtrfc, 360, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, txtrfc, 120, SpringLayout.WEST, contenedor);
        sp.putConstraint(SpringLayout.EAST, txtrfc, 350, SpringLayout.WEST, contenedor);
        txtcontraseña = new JTextField();
        contenedor.add(txtcontraseña);
        sp.putConstraint(SpringLayout.NORTH, txtcontraseña, 380, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, txtcontraseña, 120, SpringLayout.WEST, contenedor);
        sp.putConstraint(SpringLayout.EAST, txtcontraseña, 350, SpringLayout.WEST, contenedor);
        
        scroll = new JScrollPane();
        cabecera = new String[]{"Folio Empleado","Nombre","Apellidos","Correo Electronico","Telefono","Oficina",
            "Departamento","Tipo de Contrato","Estado","Ciudad","Calle","Codigo Postal","Fecha de nacimiento",
            "Puesto de trabajo","Genero","Sueldo","CURP","RFC","Contraseña"};
        dtm = new DefaultTableModel(datos,cabecera);
        tabla = new JTable(dtm);
        scroll.setViewportView(tabla);
        contenedor.add(scroll);
        sp.putConstraint(SpringLayout.NORTH, scroll, 150, SpringLayout.NORTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, scroll, 10, SpringLayout.WEST, contenedor);
        sp.putConstraint(SpringLayout.EAST, scroll, -10, SpringLayout.EAST, contenedor);
        sp.putConstraint(SpringLayout.SOUTH, scroll, -150, SpringLayout.SOUTH, contenedor);
        
        btnAdd = new JButton("Agregar");
        contenedor.add(btnAdd);
        sp.putConstraint(SpringLayout.SOUTH, btnAdd, -10, SpringLayout.SOUTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, btnAdd, 80, SpringLayout.WEST, contenedor);
        btnDel = new JButton("Borrar");
        contenedor.add(btnDel);
        sp.putConstraint(SpringLayout.SOUTH, btnDel, -10, SpringLayout.SOUTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, btnDel, 210, SpringLayout.WEST, contenedor);
        btnUpd = new JButton("Modificar");
        contenedor.add(btnUpd);
        sp.putConstraint(SpringLayout.SOUTH, btnUpd, -10, SpringLayout.SOUTH, contenedor);
        sp.putConstraint(SpringLayout.WEST, btnUpd, 330, SpringLayout.WEST, contenedor);
        setVisible(true);
    }
    
    public void conectaControlador(ControllerUsuario c){
        btnAdd.addActionListener(c);
        btnAdd.setActionCommand("INSERTAR");
        btnDel.addActionListener(c);
        btnDel.setActionCommand("BORRAR");
        btnUpd.addActionListener(c);
        btnUpd.setActionCommand("MODIFICAR");
        tabla.addMouseListener(c);
        tabla.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
}
