/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Prueba;

/**
 *
 * @author levij
 */
public class InterfazAgregarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form InterfazAgregarUsuario
     */
    public InterfazAgregarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Introduce los datos que se te piden");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(11, 4));
        jPanel1.add(jLabel2);
        jPanel1.add(jLabel3);
        jPanel1.add(jLabel4);
        jPanel1.add(jLabel5);
        jPanel1.add(jLabel6);

        jLabel7.setText("Correo Electronico");
        jPanel1.add(jLabel7);
        jPanel1.add(jTextField1);
        jPanel1.add(jLabel8);
        jPanel1.add(jLabel9);

        jLabel10.setText("Confirmar Correo ");
        jPanel1.add(jLabel10);
        jPanel1.add(jTextField2);
        jPanel1.add(jLabel11);
        jPanel1.add(jLabel12);
        jPanel1.add(jLabel13);

        jLabel14.setFont(new java.awt.Font("Dialog", 2, 8)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.add(jLabel14);
        jPanel1.add(jLabel15);
        jPanel1.add(jLabel16);

        jLabel17.setText("Nombre");
        jPanel1.add(jLabel17);
        jPanel1.add(jTextField3);
        jPanel1.add(jLabel18);
        jPanel1.add(jLabel19);

        jLabel20.setText("Apellidos");
        jPanel1.add(jLabel20);
        jPanel1.add(jTextField4);
        jPanel1.add(jLabel21);
        jPanel1.add(jLabel22);

        jLabel23.setText("Teléfono");
        jPanel1.add(jLabel23);
        jPanel1.add(jTextField5);

        jLabel24.setFont(new java.awt.Font("Dialog", 2, 8)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.add(jLabel24);
        jPanel1.add(jLabel25);

        jLabel26.setText("Contraseña");
        jPanel1.add(jLabel26);
        jPanel1.add(jTextField6);
        jPanel1.add(jLabel27);
        jPanel1.add(jLabel28);

        jLabel29.setText("Confirmar Contraseña");
        jPanel1.add(jLabel29);
        jPanel1.add(jTextField7);

        jLabel30.setFont(new java.awt.Font("Dialog", 2, 8)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.add(jLabel30);
        jPanel1.add(jLabel31);
        jPanel1.add(jLabel32);

        jButton1.setText("Continuar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregaUsuarioJButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);
        jPanel1.add(jLabel33);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        jButton2.setText("Regresar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirJButton2MouseClicked(evt);
            }
        });
        jPanel2.add(jButton2);
        jPanel2.add(jLabel34);
        jPanel2.add(jLabel35);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregaUsuarioJButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregaUsuarioJButton1MouseClicked
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jTextField2.getText())) {
            jLabel14.setText(" ");
            if (jTextField6.getText().equals(jTextField7.getText())) {
                jLabel30.setText(" ");
                UsuarioDAO us = new UsuarioDAO();
                if(us.buscarUsuarioC(jTextField1.getText()) == null){
                    jLabel14.setText(" ");
                    if(us.buscarUsuarioT(jTextField5.getText()) == null){
                        jLabel24.setText(" ");
                        us.crearUsuario(new Usuario(jTextField1.getText(),
                                jTextField3.getText(),jTextField4.getText(),
                                jTextField5.getText(),jTextField6.getText()));
                    } else {
                        jLabel24.setText("Este telefono ya esta registrado");
                    }
                } else {
                    jLabel14.setText("Este correo ya esta registrado");
                }
            } else {
                jLabel30.setText("La cotraseña no coincide");
            }
        } else{
            jLabel14.setText("El correo no coincide");
        }
        
    }//GEN-LAST:event_AgregaUsuarioJButton1MouseClicked

    private void SalirJButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirJButton2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_SalirJButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazAgregarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
